### ISSUE TITLE
Duplicate Entity IDs

### ISSUE THREAD

**Issue by Spekio** [CelestialCartographers/Loenn#15]
I've been using Lonn as much as I can for my map, but when I do open Ahorn it frequently complains about a dozen or so duplicate IDs and asks for them to fixed. Which leads me to believe that Lonn is creating entities with duplicate IDs in some instances.

**Comment by Spekio** [comment]
When drawing a single line with the Line or Rectangle tool, it frequently misses drawing the 2nd and 3rd tile.



https://user-images.githubusercontent.com/7883073/151724771-bd2f037f-5100-4d74-8610-39ffa14d6c5c.mp4

**Comment by Cruor** [comment]
This should already be fixed by commit 86e5efbe2d105e9a 🤔 
Any newly placed entities/triggers should work. There is no "reassign IDs" dialog like in Ahorn because of less wide use, and that it was a issue in Ahorn for far longer. 
Do tell me if it still happens after you let Ahorn fix the IDs.

**Comment by Spekio** [comment]
I've had it happen frequently when opening Ahorn after using Lonn. I'm on the latest version posted a week ago,
