### ISSUE TITLE
Tile Drawing Bug

### ISSUE THREAD

**Issue by Spekio** [CelestialCartographers/Loenn#16]
When drawing a single line with the Line or Rectangle tool, it frequently misses drawing the 2nd and 3rd tile. The tile will reappear if you place another tile next to it, so it does exist, it's just invisible.

https://user-images.githubusercontent.com/7883073/151724888-728773df-f69b-44b2-980f-3611a92ad089.mp4

**Comment by Cruor** [comment]
Same bug as issue #14, fixed but not in a release yet.
