### ISSUE TITLE
ZLIB_1.2.9 missing

### ISSUE THREAD

**Issue by YohananDiamond** [CelestialCartographers/Loenn#2]
I've been trying to load Loenn since a while, but I always get this error:

```
Error

error loading module 'nfd' from file './nfd.so':
/tmp/.mount_Du1T6E/usr/../lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)


Traceback

[C]: at 0x7fdc683402e0
[C]: in function 'require'
filesystem.lua:2: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:27: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:22>
[C]: in function 'require'
utils.lua:2: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:27: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:22>
[C]: in function 'require'
meta.lua:1: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:27: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:22>
[C]: in function 'require'
selene_main.lua:3: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:27: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:22>
[C]: in function 'require'
main.lua:13: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

Investigating the error message on the top, I've tried to install `zlib1.2.9` and `libpng1.6.37`, but they didn't change the problem.

OS: `Linux (Ubuntu 19.04)`
Loenn version: `v0.0.7` (It also happened with the previous version)

**Comment by Vexatos** [comment]
I mean it does look like nfd is linked against a different version of zlib. Installing the right zlib version (this issue has plenty of hits in search engines) should do it. Alternatively, you can [compile nfd yourself](https://github.com/Vexatos/nativefiledialog/tree/master/lua).

**Comment by YohananDiamond** [comment]
I've tried compiling your fork of nfd (and it was recognized by Loenn), and also tried to fix the problem with [this link](https://stackoverflow.com/questions/48306849/lib-x86-64-linux-gnu-libz-so-1-version-zlib-1-2-9-not-found), but none of them worked.

**Comment by Vexatos** [comment]
You aren't supposed to install nfd anywhere, it goes in the directory next to the .love file.

**Comment by YohananDiamond** [comment]
I knew that, and because of that I renamed the `nfd.so` file in the folder to `nfd.so.old` to see if it loaded my installed one - and it loaded, but the same error appeared.
And I've tried now to put the new nfd file I built on the Loenn folder and it still didn't change anything.

**Comment by Vexatos** [comment]
Not sure I can help you with that, it really looks like your GTK installation may be messed up somehow.

**Comment by YohananDiamond** [comment]
Okay, but thanks for trying anyway. I actually was going to re-install my OS in some days (or weeks). When I do it I'll try running Ahorn again and post updates here.

**Comment by YohananDiamond** [comment]
So, I've reinstalled my OS some weeks ago, and Loenn still didn't work.

I'll try next disabling whatever links to `nfd.so` in the code to see if it works, there only seems to be references to it in `src/filesystem.lua`.

**Comment by YohananDiamond** [comment]
I've been trying to run Loenn via its source code but, when I try to init the submodules (`git submodule update --init`), it says that there is no `giraffe` submodule in `.gitmodules`. In fact there isn't any declaration of it there, and here in GitHub the `src/giraffe` folder has a submodule icon, but can't be acessed, where `src/selene` is also a submodule but can be acessed.

**Comment by Vexatos** [comment]
Looks like Cruor did a dumb. Fixed that in https://github.com/CelestialCartographers/Loenn/commit/5ae1dcea4a21559243dfae8e7c55188e96076aa0.

**Comment by YohananDiamond** [comment]
Finally I got it to run!

Just another thing - currently there's only the navigation is available, right? I'm not sure if it's glitched for me, but it's the only thing I can do.

![image](https://user-images.githubusercontent.com/23298480/77019922-cd474b80-6960-11ea-903d-6c7fb49ddd1f.png)

It looks pretty good and is running smooth!

**Comment by Vexatos** [comment]
Indeed, this looks correct. #1 works on a basic UI, and we're working on a solution as well, but it's taking time. Ahorn is the only fully-featured editor right now.
