### ISSUE TITLE
Selection Add Modifier not working/forgotten

### ISSUE THREAD

**Issue by anexistantperson** [CelestialCartographers/Loenn#28]
If you select an object, hold shift, then try to select another one, it does not add the object to the selection but instead switches to it entirely.

I did ask someone else if they had this problem and they did. I would imagine you have forgotten to fix it or add it at some point if its gone through this many updates without being added.

**Comment by Cruor** [comment]
Its currently not hooked up, that's why its omitted from the readme currently.

**Comment by anexistantperson** [comment]
added in new update
