### ISSUE TITLE
[feature planning] better metadata window

### ISSUE THREAD

**Issue by microlith57** [CelestialCartographers/Loenn#29]
in ahorn, the metadata window is separated into _meta_, _mode_, and _audio_, but this distinction is unintuitive; _cassette song_ is in meta rather than audio, _core mode_ isn't with the other core option (in inventory); _end level on heart_ is difficult to find for beginners, etc.

as such, i suggest the following grouping for the options in the lönn window:
- **gameplay** (starting room, intro type, postcard sound?, wipe, end on heart, inventory, etc.), then a gap, then override a-side meta
- **lighting** (colourgrade, lighting, bloom)
- **audio** (ambience, music, cassette song, audio layers)
- **custom graphics** (tiles, sprites, portraits)
- **overworld** (title banner)

~~if i get time i intend to implement this.~~

**Comment by Cruor** [comment]
It is separated into those tabs because thats how they are set up in the metadata data, I already have other plans for the window than what Ahorn does.

**Comment by Cruor** [comment]
This is probably resolved at this point.
