### ISSUE TITLE
Accidental placement of decals & entities

### ISSUE THREAD

**Issue by coffe789** [CelestialCartographers/Loenn#30]
I often find random decals around the place when editing and have found the cause. If you hold down left click on something inside the right menu bar, then release it outside of the menu bar an item will be placed. One common situation this happens in is selecting text with the cursor:
![image](https://user-images.githubusercontent.com/69199627/180245225-60a74cc4-d900-40fd-a4d0-b5ca37c9366a.png)

**Comment by Cruor** [comment]
Should be fixed with https://github.com/EverestAPI/OlympUI/pull/12, thanks for the report and reproduction steps 👍 Keeping the issue open until Lönn has the OlympUI update for it.

**Comment by Cruor** [comment]
OlympUI version with this fix was merged in yesterday, closing the issue.
