### ISSUE TITLE
Selections still shown when deleting groups of entities with nodes

### ISSUE THREAD

**Issue by CaptainCarpensir** [CelestialCartographers/Loenn#35]
When deleting any entity by clicking and dragging over the entity and deleting, if any entity deleted in the process had multiple nodes, the selection and node images are still rendered until the screen is clicked on again. This happens when deleting just one entity like this, when deleting multiple entities like this, and when deleting entities both with and without nodes (the visual bug just only appears for ones with nodes). Only case where this doesn't happen is if a noded entity is deleted by directly clicking on the entity.

This happened with all noded entities I tested: Swap Blocks, Moving Platforms, Linked Sinking Platform (An unreleased custom entity of mine)

**Example:**
![Screenshot (813)](https://user-images.githubusercontent.com/72675057/189263680-fd2fdc2b-b482-4282-aa45-776613cd5b06.png)
![Screenshot (814)](https://user-images.githubusercontent.com/72675057/189263692-87341666-6627-4e0d-bf8c-ef8d29c5bebf.png)

This should be a very low priority issue as it's just a minor visual bug.

**Comment by Cruor** [comment]
Plan is to fix the visual bugs when the new selection tool comes out, the current ones needs a bit of a refactor. That probably happens at the same time as tile selections get implemented.
