### ISSUE TITLE
Loenn didn't render correctly when the "show fps" function of screen recording software is on.

### ISSUE THREAD

**Issue by Saplonily** [CelestialCartographers/Loenn#36]
I usually open celeste, screen recording software, loenn at the same time and It's convenient to share the new function of helpers or other else to my friends using recordings. But loenn seems to behave abnormally when be displayed fps, like this(use ocam):  
![image](https://user-images.githubusercontent.com/38844901/197305668-78ee3cbb-fbaf-4c5e-9ff2-baa62235189c.png)
Also I tried bandicam and it almost solve the problem but with some glitch at the bottom right corner like this:  
![image](https://user-images.githubusercontent.com/38844901/197306191-7825af29-020f-4989-bff3-807c87356cbe.png)
Sometimes it even break the render of the foreground or something more.  
It would be great if this could be solved.  
Or this could be a problem of LÖVE ...?

**Comment by Cruor** [comment]
I have no problem with this with RivaTuna (fps) or Open Broadcasting Software (recording). 
Assuming its just a issue with how your software injects/layers itself into the process.
![image](https://user-images.githubusercontent.com/2391698/197328713-4806ec65-0ac2-471e-8fc6-6c4b4a47657d.png)

**Comment by Saplonily** [comment]
seems ocam and bandicam have issues in injecting their fps layer into a program that using opengl core-profile.
closed by not related to loenn
