### ISSUE TITLE
Trouble using the Styleground menu

### ISSUE THREAD

**Issue by TheBackpack89** [CelestialCartographers/Loenn#47]
I can't set any Styleground image or anything, the arrow that usually 
appears on other's Styleground menu right to Texture apparently doesn't on mine ?
![To show](https://user-images.githubusercontent.com/126621437/221986513-6b316953-5598-4211-af2c-98d775e2ce57.png)
Idk if it's a computer or software issue but if you have a solution to this problem I'm open to anything ( :

**Comment by s0meone247** [comment]
they need to fix it, or give a solution. I have the same problem.

**Comment by Cruor** [comment]
The dropdown options were removed because they were both a horrible user experience and caused frequent crashes. The crashes might be fixed now, but I would rather have a better solution for it than enable what Ahorn has.

**Comment by s0meone247** [comment]
@TheBackpack89 Found this https://styleground-picker.modded-celeste.com
