### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by MelloBoo44** [CelestialCartographers/Loenn#48]
tried to use olympus & manually installing for win10 and it gives this when loading - cant really figure out how to use .love so i havent tried it

Error

[love "boot.lua"]:276: error loading module 'nfd' from file '.\nfd.dll':
The specified module could not be found.

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'error'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by Cruor** [comment]
Did you unzip the entire release zip before running it?

**Comment by MelloBoo44** [comment]
Yes - looking in the olympus/loenn folder there arent any zips, i unzipped everything manually w/o everest in another folder aswell and no luck-

**Comment by Terria-K** [comment]
same issue right here, it's on the root folder as well

**Comment by Cruor** [comment]
Forgot to get back to this, installing vcredist (https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) should do the trick, I guess you didn't install a random steam game that pulls down 40 versions of it 😅

**Comment by MelloBoo44** [comment]
it works! thanks
