### ISSUE TITLE
Celeste.exe is difficult to access on Mac

### ISSUE THREAD

**Issue by Zygahedron** [CelestialCartographers/Loenn#49]
Starting Lönn from Olympus the first time, it told me to select `Celeste.exe`, which isn't a normal thing on mac, so I assumed giving it `Celeste.app` (technically a directory) would work, but instead it crashed with this error:
```
Error

Editor version: 0.5.3
Love2d version: 11.3.0 - Mysterious Mysteries
Operating system: OS X

initial_startup.lua:27: attempt to call field 'isDirectory' (a nil value)


Traceback

initial_startup.lua:27: in function 'cleanupPath'
scenes/startup.lua:43: in function 'callback'
utils/filesystem.lua:358: in function 'openDialog'
scenes/startup.lua:50: in function 'checkDialog'
scenes/startup.lua:111: in function <scenes/startup.lua:103>
scene_handler.lua:46: in function 'update'
selene_main.lua:38: in function 'update'
main.lua:61: in function <main.lua:25>
[C]: in function 'xpcall'
```

My next idea was to give it the `Celeste` executable from within the .app, but you can't access that directly within the file picker dialogue, so I had to open a separate window to drag on it... but that just reopened the dialogue, so evidently that was wrong too.
It turns out there *is* a `Celeste.exe` elsewhere in the .app, so I guess the instruction isn't wrong, but it could certainly be made more clear.
Ideally, it should be able to find `Celeste.app/Contents/Resources/Celeste.exe` automatically, and update the initial text to reflect that.

**Comment by Cruor** [comment]
It already does this, your issue is a regression at some point and has already been fixed.
