### ISSUE TITLE
copying and pasting tiles crashes Loenn

### ISSUE THREAD

**Issue by f0r0f0r** [CelestialCartographers/Loenn#54]
[Video](https://cdn.discordapp.com/attachments/1079224855624417330/1128430894726774784/2023-07-11_17-00-05.mp4)
Stack trace:
`Error

Editor version: 0.7.3
Love2d version: 11.4.0 - Mysterious Mysteries
Operating system: Windows

tools/selection.lua:252: table index is nil

Traceback

[love "callbacks.lua"]:228: in function 'handler'
tools/selection.lua:252: in function 'func'
utils/drawing.lua:143: in function 'callKeepOriginalColor'
tools/selection.lua:240: in function 'func'
viewport_handler.lua:144: in function 'drawRelativeTo'
tools/selection.lua:226: in function 'drawSelectionRectanglesCommon'
tools/selection.lua:270: in function 'drawSelectionRectangles'
tools/selection.lua:1406: in function <tools/selection.lua:1392>
input_device.lua:28: in function 'propagateEvent'
scenes/editor.lua:104: in function <scenes/editor.lua:87>
scene_handler.lua:46: in function 'draw'
selene_main.lua:32: in function 'draw'
main.lua:85: in function <main.lua:25>
[C]: in function 'xpcall'`

**Comment by Cruor** [comment]
Fixed in bb7f7949b2f199ad4b3c1fdca5be0483a30d2a00, thanks!
