### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pawlisKing** [CelestialCartographers/Loenn#60]
OS: Windows 11
![Zrzut ekranu 2023-11-20 133856](https://github.com/CelestialCartographers/Loenn/assets/151532985/6a64ab19-1884-4fea-90b3-79649f8332ab)
i selected wrong version of celeste and i do not know how to restart program or uninstall it (i tried doing it from olympus but error occurred)

**Comment by Cruor** [comment]
Late to the party here, but this looks like the Windows Store version of Celeste. That version is not moddable.
