### ISSUE TITLE
Swapping between "Tileset Tools" and other tabs resets to air

### ISSUE THREAD

**Issue by SmartyNotchy** [CelestialCartographers/Loenn#62]
Swapping between any of the "Tileset Tools" (Brush, Bucket, Line, Circle, Ellipse, Rectangle) and the other tools (Placement, Selection) results in the selected tile being reset (functionally) to air. However, the visually selected tileset is still the same as before. Swapping between tilesets within the tab temporarily fixes the issue. Persists between reloads and maps.

Occurs on v0.7.7 (Latest)

Steps to Reproduce:
1) Open a map, select (for example) Brush tool with Cement tile
2) Paint some cement tiles to confirm tool is working as expected
3) Switch to the Placement tool
4) Switch back to Brush
5) Paint more cement tiles

Expected Result:
- Cement is still selected visually
- Cement tiles are placed

Observed Result:
- Cement is still selected visually
- **Air is placed instead of cement**

**Comment by Cruor** [comment]
Thanks for the report. The issue has been fixed since 5514c07ae23b1178e634d30a11d95a69b390b1d5. There just isn't a release out with it yet.
