### ISSUE TITLE
Switching between foreground brushes reverts to placing air.

### ISSUE THREAD

**Issue by SharkFinFace** [CelestialCartographers/Loenn#64]
If you select a foreground tile when using any of the tools that place them (Brush/Bucket/Circle/Ellipse/Line/Rectangle), the selector will still show the tile you selected, but it instead draws with air. This only applies to foreground tiles, not background.

Nothing game-breaking, but it is still an inconvenience.

Using latest (0.7.7).

**Comment by Cruor** [comment]
Fixed in 0.7.8
