### ISSUE TITLE
Issue: Some modules are not present while downloading the source code of loenn

### ISSUE THREAD

**Issue by MikosDrafle** [CelestialCartographers/Loenn#76]
Like in the title, some modules are not present in the source code of Loenn on download (like NativeFileDialog's lua compiled version forked by one of the creators, which doesn't let Loenn start in ZeroBrane and instead returns an error describing that nfd.lua is missing)

**Comment by Cruor** [comment]
The compiled libraries do not belong in the source code, and all modules are either included in the code or available as submodules.
