### ISSUE TITLE
Lönn β - 0.8.0 crashes on Mac when interacting with a new file.

### ISSUE THREAD

**Issue by Not-Joshing** [CelestialCartographers/Loenn#78]
The following crash and error occur when going to file-> new, and clicking on the Lönn window.

Specifications:

macOS version: Sonoma 14.5
Machine and Type: MacBook Air, Apple Silicon (M3)

Error

Editor version: 0.8.0
Love2d version: 11.3.0 - Mysterious Mysteries
Operating system: OS X

utils/brush_tool.lua:102: attempt to index local 'room' (a boolean value)

Traceback

utils/brush_tool.lua:102: in function 'hasSnapshottedRoomResized'
utils/brush_tool.lua:115: in function 'startTileSnapshot'
tools/brush.lua:66: in function <tools/brush.lua:62>
input_device.lua:28: in function <input_device.lua:15>
scene_handler.lua:46: in function 'sendEvent'
input_handler.lua:65: in function <input_handler.lua:57>
main.lua:36: in function <main.lua:25>
[C]: in function 'xpcall'

**Comment by Not-Joshing** [comment]
Tiny extra details:

1. The error occurs on the standalone Lönn app and the version on Olympus.
2. The copy error command for Mac should be command + c instead of control + c. It's a small operating system error, but it's not a huge deal.

**Comment by Cruor** [comment]
Thanks, fixed in next release.
The blue error screen text is from love2d, we only add the editor, love and os version to it.
