### ISSUE TITLE
I have an issue with loenn

### ISSUE THREAD

**Issue by N0ClueReally** [CelestialCartographers/Loenn#84]
Two Problems:
**1. Block and most entities textures do not show up**
Ive updated loenn, i have created a room also selected rectangle-cliffside 
Block textures only show up when i delete settings.conf in the "C:\Users\newuser\AppData\Local\Loenn\settings.conf" and restart the app. When i open it again the textures dont show up again. I do not change smth in the settings.
**2.Triggers blocks do not show up in the menu**
Basiclly i cant select any triggers beacuse they dontt show up. When i select it, it by default selects me to some random one (idk which).

Can you help?

https://github.com/user-attachments/assets/c3690286-02bb-42bf-a68b-2bc9031c9e1f

**Comment by N0ClueReally** [comment]
no one replyed dang..

**Comment by Cruor** [comment]
I asked you for extra info and then it turned out you had a pirated copy of Celeste, you never got back to me.
