### ISSUE TITLE
rectangles.create errors if an entity without width or height defined is sent through

### ISSUE THREAD

**Issue by 9thCore** [CelestialCartographers/Loenn#85]
terrible at explaining so example

Minimum reproducible:
```lua
local connectedEntities = require("helpers.connected_entities");

return {
	name = "CoreHelper/Wire",
	placements = {
		name = "default"
	},
	sprite = function(room)
		connectedEntities.getEntityRectangles(room.entities); -- or just iteration over room.entities and constructing rectangles manually, its the same thing anyway
	end
};
```

This makes it such that, the moment there is an unresizable entity in the same room as `Wire`, it will turn into a red rectangle (errored) and spam this error in the log:
```lua
[WARNING] Erroring entity definition for 'CoreHelper/Wire' in room 'room00' at (184, 112) when rendering
[WARNING] [string "structs/rectangle.lua"]:12: attempt to compare nil with number
stack traceback:
	[string "entities.lua"]:43: in function 'logEntityDefinitionError'
	[string "entities.lua"]:375: in function 'getDrawable'
	[string "celeste_render.lua"]:621: in function 'func'
	[string "utils/tasks.lua"]:203: in function <[string "utils/tasks.lua"]:203>
```

in a way, this makes sense, as width and height arent defined as data for these, but there should really be some sort of default (such as texture width/height?) i'd reckon.. presumably in the entity object itself would make the most sense

**Comment by Cruor** [comment]
Are you sure you don't want to filter the entities you are looking over? The connected entities are intended to be used on "blocks", and not really more than that 😓

**Comment by 9thCore** [comment]
yeah, thats fair.. for my particular use-case, i *would* need non-resizable entities as i'd need to connect resizable entities to non-resizable ones, but i do now realise it is an, admittedly, much too complex idea and too niche of a use-case (which i do simply just work around by hardcoding the entity's size with a custom implementation of the function, so its not that big a deal)

and since this issue hasnt been picked up or asked about since... at least 4 years? its probably fine to close it right about now; sorry for the disturb
